# Generated by Django 3.2.4 on 2021-07-14 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210713_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_created',
        ),
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 11, 22, 34, 933843)),
        ),
    ]
